gvpr getval: fix use of uninitialized 'v'
CI has begun failing on macOS:

  [ 33%] Building C object lib/gvpr/CMakeFiles/gvpr.dir/compile.c.o
  lib/gvpr/compile.c:1480:11: error: variable 'v' is used uninitialized
    whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
   1480 |       if (state->infname == NULL) {
        |           ^~~~~~~~~~~~~~~~~~~~~~
  lib/gvpr/compile.c:1508:12: note: uninitialized use occurs here
   1508 |     return v;
        |            ^
  lib/gvpr/compile.c:1480:7: note: remove the 'if' if its condition is
    always false
   1480 |       if (state->infname == NULL) {
        |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   1481 |         agxbuf xb = {0};
        |         ~~~~~~~~~~~~~~~~
   1482 |         exerror("current input file is not defined for %s",
        |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   1483 |                 deparse(pgm, node, &xb));
        |                 ~~~~~~~~~~~~~~~~~~~~~~~~~
   1484 |         agxbfree(&xb);
        |         ~~~~~~~~~~~~~~
   1485 |       } else {
        |       ~~~~~~
  lib/gvpr/compile.c:565:3: note: variable 'v' is declared here
    565 |   Extype_t v;
        |   ^

The cause is that 72da23731130700af17d9e78c27e187d695d0961 added a
control flow path that does not assign `v`.

Reported-by: AppleClang 17.0.0.17000013 -Wsometimes-uninitialized